rails_lessons/devise_and_carrierwave_examples/zombie_manager/config/routes.rb
ZombieManager::Application.routes.draw do
  devise_for :zombies

  resources :humans

  root :to => 'humans#index'

end

rails_lessons/devise_and_carrierwave_examples/zombie_manager/app/models/human.rb
class Human < ActiveRecord::Base
  attr_accessible :blood_type, :height, :weight, :picture, :picture_cache
  mount_uploader :picture, PictureUploader
end

rails_lessons/devise_and_carrierwave_examples/zombie_manager/app/models/zombie.rb
class Zombie < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

rails_lessons/devise_and_carrierwave_examples/zombie_manager/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_zombie!, :except => [:index]
end

rails_lessons/devise_and_carrierwave_examples/zombie_manager/app/controllers/humans_controller.rb
class HumansController < ApplicationController
  # GET /humans
  # GET /humans.json
  def index
    @humans = Human.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @humans }
    end
  end

  # GET /humans/1
  # GET /humans/1.json
  def show
    @human = Human.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @human }
    end
  end

  # GET /humans/new
  # GET /humans/new.json
  def new
    @human = Human.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @human }
    end
  end

  # GET /humans/1/edit
  def edit
    @human = Human.find(params[:id])
  end

  # POST /humans
  # POST /humans.json
  def create
    @human = Human.new(params[:human])

    respond_to do |format|
      if @human.save
        format.html { redirect_to @human, notice: 'Human was successfully created.' }
        format.json { render json: @human, status: :created, location: @human }
      else
        format.html { render action: "new" }
        format.json { render json: @human.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /humans/1
  # PUT /humans/1.json
  def update
    @human = Human.find(params[:id])

    respond_to do |format|
      if @human.update_attributes(params[:human])
        format.html { redirect_to @human, notice: 'Human was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @human.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /humans/1
  # DELETE /humans/1.json
  def destroy
    @human = Human.find(params[:id])
    @human.destroy

    respond_to do |format|
      format.html { redirect_to humans_url }
      format.json { head :no_content }
    end
  end
end

rails_lessons/devise_and_carrierwave_examples/zombie_manager/app/helpers/humans_helper.rb
module HumansHelper
end

rails_lessons/devise_and_carrierwave_examples/zombie_manager/app/views/humans/_form.html.erb
<%= form_for @human, :html => {:multipart => true} do |f| %>
  <% if @human.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@human.errors.count, "error") %> prohibited this human from being saved:</h2>

      <ul>
      <% @human.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :blood_type %><br />
    <%= f.text_field :blood_type %>
  </div>
  <div class="field">
    <%= f.label :height %><br />
    <%= f.text_field :height %>
  </div>
  <div class="field">
    <%= f.label :weight %><br />
    <%= f.text_field :weight %>
  </div>
  <div>
    <%= f.label :picture %></br>
    <%= image_tag(@human.picture_url) if @human.picture? %>
    <%= f.file_field :picture %>
    <%= f.hidden_field :picture_cache %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rails_lessons/devise_and_carrierwave_examples/zombie_manager/app/views/humans/edit.html.erb
<h1>Editing human</h1>

<%= render 'form' %>

<%= link_to 'Show', @human %> |
<%= link_to 'Back', humans_path %>

rails_lessons/devise_and_carrierwave_examples/zombie_manager/app/views/humans/index.html.erb
<h1>Listing humans</h1>

<table>
  <tr>
    <th>Pictre</th>
    <th>Blood type</th>
    <th>Height</th>
    <th>Weight</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @humans.each do |human| %>
  <tr>
    <td><%= image_tag(human.picture_url) if human.picture? %></td>
    <td><%= human.blood_type %></td>
    <td><%= human.height %></td>
    <td><%= human.weight %></td>
    <td><%= link_to 'Show', human %></td>
    <td><%= link_to 'Edit', edit_human_path(human) %></td>
    <td><%= link_to 'Destroy', human, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Human', new_human_path %>

rails_lessons/devise_and_carrierwave_examples/zombie_manager/app/views/humans/new.html.erb
<h1>New human</h1>

<%= render 'form' %>

<%= link_to 'Back', humans_path %>

rails_lessons/devise_and_carrierwave_examples/zombie_manager/app/views/humans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Blood type:</b>
  <%= @human.blood_type %>
</p>

<p>
  <b>Height:</b>
  <%= @human.height %>
</p>

<p>
  <b>Weight:</b>
  <%= @human.weight %>
</p>


<%= link_to 'Edit', edit_human_path(@human) %> |
<%= link_to 'Back', humans_path %>

rails_lessons/devise_and_carrierwave_examples/zombie_manager/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ZombieManager</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if zombie_signed_in? %>
You are Signed In as <%= current_zombie.email %>
<%= link_to 'Sign Out', destroy_zombie_session_path, :method => :delete %>
<% else %>
<%= link_to 'Sign In', new_zombie_session_path %>
<% end %>
<%= yield %>

</body>
</html>